---
title: "806_final"
author: "Megan Worth"
date: "11/8/2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---
**Introduction**

**Methods**

**Results**

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}

sup_data <- read.csv("C:/Users/megan/Desktop/806_final/supp_data1.csv", stringsAsFactors = TRUE)

lake_data <- read.csv("C:/Users/megan/Desktop/806_final/lake_data1.csv", stringsAsFactors = TRUE)

otu_data <- read.csv("C:/Users/megan/Desktop/806_final/otu_data1.csv", stringsAsFactors = TRUE)

rel_abun <- read.csv("C:/Users/megan/Desktop/806_final/rel_abun1.csv", stringsAsFactors = TRUE)

```

```{r, echo = FALSE}
library(dplyr)
library(tidyr)
```

```{r, echo = FALSE}

comb1 <- inner_join(otu_data, rel_abun, by = "OTU")
comb2 <- inner_join(sup_data, lake_data)
database <- inner_join(comb1, comb2)


```

```{r, echo = FALSE}
# come back to this later
library(ggplot2)
select(database, Phylum, value, pH, Year) %>%
  filter(Year == 2009, pH > 0) %>% 
  ggplot(mapping = aes(fill = Phylum, x = pH, y = value, color =
  Phylum)) + geom_bar(position="stack", stat="identity") + 
  labs(x = "pH", y = "Abundance") +
  theme(legend.text = element_text(size = 6), 
  legend.key.size = unit(0.5, "cm"), 
  legend.key.height = unit(0.5, "cm"),  
  legend.key.width = unit(0.5, "cm"))

```

# this plot shows abundance of microbes by varying pH in Crystal Bog
```{r, echo = FALSE}

select(database, Lake, Phylum, value, pH) %>%
  filter(pH > 0) %>% 
  ggplot(mapping = aes(x = pH, y = value)) + geom_bar(stat="identity") + 
  labs(x = "pH", y = "Abundance") 

```

# space to practice making graphs / not finalized
```{r, echo = FALSE}

select(database, Month, Year, Temperature) %>%
  filter(Temperature > 0) %>% 
  ggplot(mapping = aes(x = Month, y = Temperature, by = Year)) + labs(x = "Month", y = "Temperature (C)") + geom_line() + geom_point()

```

# practice graph space
```{r, echo = FALSE}

select(database, Lake, Temperature, Month, Year) %>%
  filter(Year == 2007, Temperature != "NA") %>% 
  ggplot(mapping = aes(x = Month, y = Temperature, color = Lake)) +
  geom_point() + geom_line()

```

```{r, echo = FALSE}

select(database, Month, Year, Temperature) %>%
  group_by(Month, Year) %>%
  filter(Temperature != "NA") %>%
  summarize(mean_temp = mean(Temperature)) %>%
  ggplot(mapping = aes(x = Month, y = mean_temp, color = 
  Year, group = Year)) + geom_point() + geom_line() + labs(color = 
  "Year", x = "Month", y = "Temperature (C)")

```

```{r, echo = FALSE}

select(database, Month, Year, DO, Lake) %>%
  group_by(Lake, Month) %>%
  filter(DO != "NA", Year == 2007) %>%
  summarize(mean_DO = mean(DO)) %>%
  ggplot(mapping = aes(x = Month, y = mean_DO, color = 
  Lake, group = Lake)) + geom_point() + geom_line() + labs(color = 
  "Lake", x = "Month", y = "Dissolved Oxygen (DO)")

```

```{r, echo = FALSE}

select(database, Month, Year, pH, Lake) %>%
  group_by(Lake, Month) %>%
  filter(pH != "NA", Year == 2009) %>%
  summarize(mean_pH = mean(pH)) %>%
  ggplot(mapping = aes(x = Month, y = mean_pH, color = 
  Lake, group = Lake)) + geom_point() + geom_line() + labs(color = 
  "Lake", x = "Month", y = "pH")

```


**Discussion**



**References**



